/*
 * A314Mount - GadTools GUI front end (AmigaOS 3.x, no external deps)
 *
 *  +------------------------------------------------+
 *  |  Drive  [ PD0: v]        [x] Read-write         |
 *  |  Image  [/home/pi/Workbench.adf____________]    |
 *  |  [ Insert ] [ Eject ]        Ready             |
 *  |  Host [127.0.0.1______]  Port [23890__]        |
 *  +------------------------------------------------+
 *
 * Mounts an ADF (floppy) or HDF (hard-disk) image on one of the a314 virtual
 * drives PD0:-PD3:. Insert/Eject send one line to the a314 disk daemon over
 * bsdsocket (a314bsd), then report the result in the status line.
 */

#include <exec/types.h>
#include <exec/lists.h>
#include <exec/nodes.h>
#include <exec/memory.h>
#include <intuition/intuition.h>
#include <libraries/gadtools.h>
#include <dos/dos.h>
#include <dos/dostags.h>

#include <proto/exec.h>
#include <proto/dos.h>
#include <proto/intuition.h>
#include <proto/graphics.h>
#include <proto/gadtools.h>

#include <string.h>

#include "a314disk.h"

/* The custom Pi browser starts here; navigate up/down from it. Unlike an ASL
 * requester (which only sees Amiga volumes), this asks the daemon to list real
 * Pi directories, so it returns absolute Pi paths directly. */
#define A314_BROWSE_ROOT "/home"

unsigned long __stack = 16000;

static const char verstag[] __attribute__((used)) =
    "$VER: A314MountGUI 0.1.1 (02.10.2026)";

struct IntuitionBase *IntuitionBase = NULL;
struct GfxBase       *GfxBase       = NULL;
struct Library       *GadToolsBase  = NULL;

enum { GAD_DRIVE = 1, GAD_RW, GAD_ADF, GAD_INSERT, GAD_EJECT, GAD_STATUS,
       GAD_HOST, GAD_PORT, GAD_BROWSE };

struct Gui {
    struct Screen *scr;
    APTR           vi;
    struct Window *win;
    struct Gadget *glist;
    struct Gadget *gDrive, *gRW, *gAdf, *gInsert, *gEject, *gStatus, *gHost, *gPort;
    struct Menu   *menu;

    char  status[80];
    char  saveAdf[210];
    char  saveHost[64];
    char  savePort[16];
    WORD  drive;          /* 0 = PD0:, 1 = PD1: */
    BOOL  rw;
    WORD  prevW;          /* last window width, to ignore no-op NEWSIZE */
};

static STRPTR driveLabels[] = { (STRPTR)"PD0:", (STRPTR)"PD1:",
                                (STRPTR)"PD2:", (STRPTR)"PD3:", NULL };

/* A small 24x11 folder image for the "browse" button on the Image row.
 * (planar, depth 2 - generated by tools; see project notes) */
#define FOLDER_W 24
#define FOLDER_H 11
static UWORD folderImageData[] = {
    0x0000, 0x0100, 0x0000, 0x0100, 0x0fc0, 0x0100, 0x0fc0, 0x0100,
    0x1fff, 0xf900, 0x1fff, 0xf900, 0x1fff, 0xf900, 0x1fff, 0xf900,
    0x1fff, 0xf900, 0x1fff, 0xf900, 0x7fff, 0xff00, 0xffff, 0xfe00,
    0x8000, 0x0000, 0x8000, 0x0000, 0x8fc0, 0x0000, 0x8000, 0x0000,
    0x8fff, 0xf000, 0x8fff, 0xf000, 0x8fff, 0xf000, 0x8fff, 0xf000,
    0x8000, 0x0000, 0x8000, 0x0000,
};
static struct Image folderImage = {
    0, 0, FOLDER_W, FOLDER_H, 2, folderImageData, 0x3, 0x0, NULL
};
static struct Gadget browseGad = {
    NULL, 0, 0, FOLDER_W, FOLDER_H,
    GFLG_GADGIMAGE | GFLG_GADGHCOMP, GACT_RELVERIFY, GTYP_BOOLGADGET,
    (APTR)&folderImage, NULL, NULL, 0, NULL, GAD_BROWSE, NULL
};

#define MENU_QUIT 1
static struct NewMenu amiNewMenu[] = {
    { NM_TITLE, (STRPTR)"Project", NULL,        0, 0, NULL },
    { NM_ITEM,  (STRPTR)"Quit",    (STRPTR)"Q", 0, 0, (APTR)MENU_QUIT },
    { NM_END,   NULL,              NULL,        0, 0, NULL }
};

static CONST_STRPTR gadStr(struct Gadget *g)
{
    struct StringInfo *si = (struct StringInfo *)g->SpecialInfo;
    return (CONST_STRPTR)si->Buffer;
}

static void setStatus(struct Gui *g, CONST_STRPTR t)
{
    strncpy(g->status, (const char *)t, sizeof g->status - 1);
    g->status[sizeof g->status - 1] = '\0';
    if (g->gStatus)
        GT_SetGadgetAttrs(g->gStatus, g->win, NULL, GTTX_Text, (ULONG)g->status, TAG_END);
}

/* ---- custom Pi-directory browser (a file requester over the daemon) ------- */

enum { BGAD_LIST = 1, BGAD_PARENT, BGAD_OPEN, BGAD_CANCEL };

struct BItem {              /* one directory entry, node.ln_Name = disp */
    struct Node node;
    UBYTE isDir;
    char  name[128];        /* raw name, for navigation                */
    char  disp[132];        /* shown name (dirs get a trailing '/')     */
};

struct Browser {
    struct Gui    *g;
    struct Window *win;
    struct Gadget *glist, *gList, *gPath;
    struct List    items;
    char  curdir[300];
    WORD  selected;
};

static void bInitList(struct List *l)
{
    l->lh_Head     = (struct Node *)&l->lh_Tail;
    l->lh_Tail     = NULL;
    l->lh_TailPred = (struct Node *)&l->lh_Head;
    l->lh_Type = 0; l->l_pad = 0;
}

static void bFreeItems(struct List *l)
{
    struct Node *n;
    while ((n = RemHead(l))) FreeVec(n);
}

/* TRUE if name (length len) ends in .adf/.hdf/.adz (case-insensitive) */
static int bImageExt(const char *s, int len)
{
    static const char ext[3][5] = { ".adf", ".hdf", ".adz" };
    int i, k;
    for (i = 0; i < 3; i++) {
        if (len >= 4) {
            int m = 1;
            for (k = 0; k < 4; k++) {
                char a = s[len - 4 + k];
                if (a >= 'A' && a <= 'Z') a = (char)(a + 32);
                if (a != ext[i][k]) { m = 0; break; }
            }
            if (m) return 1;
        }
    }
    return 0;
}

/* Parse the output of `ls -1Ap` (dirs have a trailing '/'). Call with
 * wantDir=1 first, then wantDir=0, to list subdirectories before files.
 * Files are filtered to image types. */
static void bParseLs(struct List *l, const char *buf, int wantDir)
{
    const char *p = buf;
    while (*p) {
        const char *eol = p; int len, isDir, nl;
        while (*eol && *eol != '\n') eol++;
        len = (int)(eol - p);
        while (len > 0 && (p[len - 1] == '\r' || p[len - 1] == ' ')) len--;
        if (len > 0) {
            isDir = (p[len - 1] == '/');
            nl = isDir ? len - 1 : len;
            if (isDir == wantDir && nl > 0 && (isDir || bImageExt(p, nl))) {
                struct BItem *it = (struct BItem *)AllocVec(sizeof(struct BItem), MEMF_CLEAR);
                if (it) {
                    int cn = nl; if (cn > 126) cn = 126;
                    memcpy(it->name, p, cn); it->name[cn] = '\0';
                    strcpy(it->disp, it->name);
                    it->isDir = (UBYTE)isDir;
                    if (isDir) strcat(it->disp, "/");
                    it->node.ln_Name = it->disp;
                    AddTail(l, &it->node);
                }
            }
        }
        p = *eol ? eol + 1 : eol;
    }
}

static struct BItem *bItemAt(struct List *l, int idx)
{
    struct Node *n = l->lh_Head; int i = 0;
    if (idx < 0) return NULL;
    while (n->ln_Succ) { if (i == idx) return (struct BItem *)n; n = n->ln_Succ; i++; }
    return NULL;
}

static void bJoin(const char *dir, const char *name, char *out, int outsize)
{
    int p = 0, i;
    for (i = 0; dir[i] && p < outsize - 1; i++) out[p++] = dir[i];
    if (p > 0 && out[p - 1] != '/' && p < outsize - 1) out[p++] = '/';
    for (i = 0; name[i] && p < outsize - 1; i++) out[p++] = name[i];
    out[p] = '\0';
}

static void bParentOf(const char *dir, char *out, int outsize)
{
    int len = (int)strlen(dir), i, last = -1;
    for (i = 0; i < len; i++) if (dir[i] == '/') last = i;
    if (last <= 0) { strcpy(out, "/"); return; }
    if (last >= outsize) last = outsize - 1;
    memcpy(out, dir, last); out[last] = '\0';
}

/* List a Pi directory by running the standard a314 `pi` command
 * (`pi ls -1Ap <dir>`) and capturing its output — no daemon patch needed.
 * Returns bytes read into buf (>=0), or -1 on failure. */
static LONG piListDir(CONST_STRPTR dir, char *buf, int bufsize)
{
    char cmd[400];
    BPTR out, in;
    LONG total = 0, rc;
    int p = 0, i;
    const char *pre = "C:pi ls -1Ap ";
    for (i = 0; pre[i] && p < (int)sizeof cmd - 1; i++) cmd[p++] = pre[i];
    for (i = 0; dir[i] && p < (int)sizeof cmd - 1; i++) cmd[p++] = dir[i];
    cmd[p] = '\0';

    /* pi refuses a redirected (non-interactive) stdin, so give it an AUTO
     * console — it stays closed unless actually read from. */
    in  = Open((STRPTR)"CON:0/0/300/40/A314Mount/AUTO/CLOSE/INACTIVE", MODE_OLDFILE);
    out = Open((STRPTR)"RAM:a314list.tmp", MODE_NEWFILE);
    if (!out) { if (in) Close(in); return -1; }

    /* run the command, capturing its output into the file (synchronous).
     * NB: this dos.library does NOT close SYS_Input/SYS_Output for us, so we
     * close them ourselves (the write handle must be closed before we can
     * re-open the file to read it). */
    rc = SystemTags((STRPTR)cmd,
        SYS_Input,  (ULONG)in,
        SYS_Output, (ULONG)out,
        SYS_Asynch, FALSE,
        TAG_END);
    (void)rc;
    Close(out);
    if (in) Close(in);

    out = Open((STRPTR)"RAM:a314list.tmp", MODE_OLDFILE);
    if (out) {
        total = Read(out, buf, bufsize - 1);
        if (total < 0) total = 0;
        Close(out);
    }
    buf[total] = '\0';
    DeleteFile((STRPTR)"RAM:a314list.tmp");
    return total;
}

/* re-list b->curdir into the listview (subdirectories first, then images) */
static void bRefresh(struct Browser *b)
{
    char *reply;

    GT_SetGadgetAttrs(b->gList, b->win, NULL, GTLV_Labels, ~0, TAG_END);
    bFreeItems(&b->items);
    b->selected = -1;

    reply = (char *)AllocVec(16384, MEMF_CLEAR);
    if (reply) {
        LONG n = piListDir((CONST_STRPTR)b->curdir, reply, 16384);
        if (n > 0) { bParseLs(&b->items, reply, 1); bParseLs(&b->items, reply, 0); }
        FreeVec(reply);
    }
    GT_SetGadgetAttrs(b->gList, b->win, NULL,
        GTLV_Labels, (ULONG)&b->items, GTLV_Selected, ~0, GTLV_Top, 0, TAG_END);
    GT_SetGadgetAttrs(b->gPath, b->win, NULL, GTTX_Text, (ULONG)b->curdir, TAG_END);
}

static void bChoose(struct Browser *b, struct BItem *it)
{
    struct Gui *g = b->g;
    char path[300];
    bJoin(b->curdir, it->name, path, (int)sizeof path);
    strncpy(g->saveAdf, path, sizeof g->saveAdf - 1);
    g->saveAdf[sizeof g->saveAdf - 1] = '\0';
    GT_SetGadgetAttrs(g->gAdf, g->win, NULL, GTST_String, (ULONG)g->saveAdf, TAG_END);
    setStatus(g, "Image selected - click Insert.");
}

/* Open the browser, let the user pick a Pi image, drop its path in the field. */
static void doBrowse(struct Gui *g)
{
    struct Browser b;
    struct NewGadget ng;
    struct Gadget *gad;
    struct Screen *sc = g->scr;
    WORD winw, winh, cl, cr, y, by, gh, row;
    BOOL done = FALSE;

    memset(&b, 0, sizeof b);
    b.g = g; b.selected = -1;
    bInitList(&b.items);
    strcpy(b.curdir, A314_BROWSE_ROOT);

    gh  = (WORD)((sc->Font ? sc->Font->ta_YSize : 8) + 3);
    row = gh + 3;
    winw = 360; if (winw > sc->Width) winw = sc->Width;
    winh = 200; if (winh > sc->Height - sc->BarHeight - 2) winh = sc->Height - sc->BarHeight - 2;

    b.win = OpenWindowTags(NULL,
        WA_Title,     (ULONG)"Select image on the Pi",
        WA_Left,      (sc->Width - winw) / 2, WA_Top, sc->BarHeight + 10,
        WA_Width,     winw, WA_Height, winh,
        WA_Flags,     WFLG_DRAGBAR | WFLG_DEPTHGADGET | WFLG_CLOSEGADGET | WFLG_ACTIVATE,
        WA_IDCMP,     IDCMP_CLOSEWINDOW | IDCMP_REFRESHWINDOW | LISTVIEWIDCMP | BUTTONIDCMP,
        WA_PubScreen, (ULONG)sc,
        TAG_END);
    if (!b.win) { bFreeItems(&b.items); return; }
    WindowToFront(b.win);
    ActivateWindow(b.win);

    cl = b.win->BorderLeft + 4;
    cr = b.win->Width - b.win->BorderRight - 4;
    y  = b.win->BorderTop + 2;
    by = winh - b.win->BorderBottom - gh - 3;      /* button row */

    gad = CreateContext(&b.glist);
    memset(&ng, 0, sizeof ng);
    ng.ng_VisualInfo = g->vi; ng.ng_TextAttr = sc->Font;

    ng.ng_LeftEdge = cl; ng.ng_TopEdge = y; ng.ng_Width = cr - cl; ng.ng_Height = gh;
    ng.ng_Flags = 0; ng.ng_GadgetID = 0;
    gad = b.gPath = CreateGadget(TEXT_KIND, gad, &ng,
                                 GTTX_Text, (ULONG)b.curdir, GTTX_Border, TRUE, TAG_END);

    ng.ng_TopEdge = y + row; ng.ng_Height = by - (y + row) - 3; ng.ng_Width = cr - cl;
    ng.ng_GadgetID = BGAD_LIST;
    gad = b.gList = CreateGadget(LISTVIEW_KIND, gad, &ng,
                                 GTLV_Labels, (ULONG)&b.items,
                                 GTLV_ShowSelected, 0L, GTLV_Selected, ~0, TAG_END);

    ng.ng_TopEdge = by; ng.ng_Height = gh; ng.ng_Width = 90;
    ng.ng_LeftEdge = cl;      ng.ng_GadgetText = (UBYTE *)"Parent"; ng.ng_GadgetID = BGAD_PARENT;
    gad = CreateGadget(BUTTON_KIND, gad, &ng, TAG_END);
    ng.ng_LeftEdge = cl + 96; ng.ng_GadgetText = (UBYTE *)"Open";   ng.ng_GadgetID = BGAD_OPEN;
    gad = CreateGadget(BUTTON_KIND, gad, &ng, TAG_END);
    ng.ng_LeftEdge = cr - 90; ng.ng_GadgetText = (UBYTE *)"Cancel"; ng.ng_GadgetID = BGAD_CANCEL;
    gad = CreateGadget(BUTTON_KIND, gad, &ng, TAG_END);

    if (gad) {
        AddGList(b.win, b.glist, ~0, -1, NULL);
        RefreshGList(b.glist, b.win, NULL, -1);
        GT_RefreshWindow(b.win, NULL);
    }
    bRefresh(&b);

    while (!done) {
        struct IntuiMessage *im;
        WaitPort(b.win->UserPort);
        while ((im = GT_GetIMsg(b.win->UserPort))) {
            ULONG cls = im->Class; UWORD code = im->Code;
            struct Gadget *gd = (struct Gadget *)im->IAddress;
            GT_ReplyIMsg(im);
            switch (cls) {
            case IDCMP_CLOSEWINDOW:
                done = TRUE; break;
            case IDCMP_GADGETUP:
                switch (gd->GadgetID) {
                case BGAD_LIST:   b.selected = (WORD)code; break;
                case BGAD_PARENT: { char p[300]; bParentOf(b.curdir, p, (int)sizeof p);
                                    strcpy(b.curdir, p); bRefresh(&b); } break;
                case BGAD_OPEN: {
                    struct BItem *it = bItemAt(&b.items, b.selected);
                    if (it) {
                        if (it->isDir) { char p[300]; bJoin(b.curdir, it->name, p, (int)sizeof p);
                                         strcpy(b.curdir, p); bRefresh(&b); }
                        else { bChoose(&b, it); done = TRUE; }
                    }
                } break;
                case BGAD_CANCEL: done = TRUE; break;
                }
                break;
            case IDCMP_REFRESHWINDOW:
                GT_BeginRefresh(b.win); GT_EndRefresh(b.win, TRUE); break;
            }
            if (done) break;
        }
    }

    GT_SetGadgetAttrs(b.gList, b.win, NULL, GTLV_Labels, ~0, TAG_END);
    CloseWindow(b.win);
    FreeGadgets(b.glist);
    bFreeItems(&b.items);
}

/* ------------------------------------------------------------------ */

static void doOp(struct Gui *g, BOOL insert)
{
    char cmd[300], reply[160];
    CONST_STRPTR adf  = gadStr(g->gAdf);
    CONST_STRPTR host = gadStr(g->gHost);
    CONST_STRPTR ports = gadStr(g->gPort);
    UWORD port = 0;
    LONG r;
    int i;

    for (i = 0; ports[i] >= '0' && ports[i] <= '9'; i++) port = (UWORD)(port * 10 + (ports[i] - '0'));
    if (port == 0) port = A314_DEF_PORT;
    if (!host || host[0] == '\0') host = (CONST_STRPTR)A314_DEF_HOST;

    if (insert && (!adf || adf[0] == '\0')) { doBrowse(g); return; }

    setStatus(g, insert ? "Inserting..." : "Ejecting...");
    if (insert) {
        r = a314Insert(host, port, g->drive, adf, g->rw, reply, (int)sizeof reply);
    } else {
        a314BuildEject(cmd, (int)sizeof cmd, g->drive);
        r = a314SendCommand(host, port, cmd, reply, (int)sizeof reply);
    }
    if (r == A314_OK) {
        char buf[80];
        strcpy(buf, "PD");
        buf[2] = (char)('0' + g->drive); buf[3] = '\0';
        strcat(buf, insert ? ": inserted" : ": ejected");
        setStatus(g, reply[0] ? (CONST_STRPTR)reply : (CONST_STRPTR)buf);
    } else {
        setStatus(g, a314ErrText(r));
    }
}

/* ------------------------------------------------------------------ */

static BOOL makeGadgets(struct Gui *g)
{
    struct NewGadget ng;
    struct Gadget *gad;
    struct Window *w = g->win;
    WORD fh = g->scr->Font ? g->scr->Font->ta_YSize : 8;
    WORD cl = w->BorderLeft + 2;
    WORD cr = w->Width - w->BorderRight - 2;
    WORD row = fh + 6, gh = fh + 3, lab = 46;
    WORD y = w->BorderTop + 2;

    gad = CreateContext(&g->glist);
    if (!gad) return FALSE;
    memset(&ng, 0, sizeof ng);
    ng.ng_VisualInfo = g->vi;
    ng.ng_TextAttr   = g->scr->Font;

    /* Drive cycle + Read-write checkbox */
    ng.ng_LeftEdge = cl + lab; ng.ng_TopEdge = y; ng.ng_Width = 70; ng.ng_Height = gh;
    ng.ng_GadgetText = (UBYTE *)"Drive"; ng.ng_Flags = PLACETEXT_LEFT; ng.ng_GadgetID = GAD_DRIVE;
    gad = g->gDrive = CreateGadget(CYCLE_KIND, gad, &ng,
                                   GTCY_Labels, (ULONG)driveLabels,
                                   GTCY_Active, (ULONG)g->drive, TAG_END);
    ng.ng_LeftEdge = cr - 22; ng.ng_Width = 22;
    ng.ng_GadgetText = (UBYTE *)"Read-write"; ng.ng_Flags = PLACETEXT_LEFT; ng.ng_GadgetID = GAD_RW;
    gad = g->gRW = CreateGadget(CHECKBOX_KIND, gad, &ng, GTCB_Checked, (ULONG)g->rw, TAG_END);

    /* Image path (ADF/HDF) + a folder button that opens a file requester */
    y += row;
    ng.ng_LeftEdge = cl + lab; ng.ng_TopEdge = y;
    ng.ng_Width = cr - (cl + lab) - FOLDER_W - 4; ng.ng_Height = gh;
    ng.ng_GadgetText = (UBYTE *)"Image"; ng.ng_Flags = PLACETEXT_LEFT; ng.ng_GadgetID = GAD_ADF;
    gad = g->gAdf = CreateGadget(STRING_KIND, gad, &ng,
                                 GTST_MaxChars, 200, GTST_String, (ULONG)g->saveAdf, TAG_END);
    browseGad.LeftEdge = cr - FOLDER_W;
    browseGad.TopEdge  = y + (gh - FOLDER_H) / 2;

    /* Insert / Eject + status */
    y += row;
    ng.ng_LeftEdge = cl; ng.ng_TopEdge = y; ng.ng_Width = 72; ng.ng_Height = gh;
    ng.ng_GadgetText = (UBYTE *)"Insert"; ng.ng_Flags = 0; ng.ng_GadgetID = GAD_INSERT;
    gad = g->gInsert = CreateGadget(BUTTON_KIND, gad, &ng, TAG_END);
    ng.ng_LeftEdge = cl + 78;
    ng.ng_GadgetText = (UBYTE *)"Eject"; ng.ng_GadgetID = GAD_EJECT;
    gad = g->gEject = CreateGadget(BUTTON_KIND, gad, &ng, TAG_END);
    ng.ng_LeftEdge = cl + 158; ng.ng_Width = cr - (cl + 158); if (ng.ng_Width < 8) ng.ng_Width = 8;
    ng.ng_GadgetText = NULL; ng.ng_GadgetID = GAD_STATUS;
    gad = g->gStatus = CreateGadget(TEXT_KIND, gad, &ng,
                                    GTTX_Text, (ULONG)g->status, GTTX_Border, FALSE, TAG_END);

    /* Host / Port */
    y += row;
    ng.ng_LeftEdge = cl + lab; ng.ng_TopEdge = y; ng.ng_Width = (cr - (cl + lab)) / 2 - 30; ng.ng_Height = gh;
    ng.ng_GadgetText = (UBYTE *)"Host"; ng.ng_Flags = PLACETEXT_LEFT; ng.ng_GadgetID = GAD_HOST;
    gad = g->gHost = CreateGadget(STRING_KIND, gad, &ng,
                                  GTST_MaxChars, 60, GTST_String, (ULONG)g->saveHost, TAG_END);
    ng.ng_LeftEdge = cr - 60; ng.ng_Width = 60;
    ng.ng_GadgetText = (UBYTE *)"Port"; ng.ng_GadgetID = GAD_PORT;
    gad = g->gPort = CreateGadget(STRING_KIND, gad, &ng,
                                  GTST_MaxChars, 6, GTST_String, (ULONG)g->savePort, TAG_END);
    return (gad != NULL);
}

/* GadTools gadgets don't reflow on their own; on a resize we snapshot the
 * field contents, tear the gadgets down, clear the interior, and rebuild them
 * at the new width. */
static void rebuildGadgets(struct Gui *g)
{
    if (g->gAdf)  { strncpy(g->saveAdf,  (const char *)gadStr(g->gAdf),  sizeof g->saveAdf - 1);  g->saveAdf[sizeof g->saveAdf - 1] = '\0'; }
    if (g->gHost) { strncpy(g->saveHost, (const char *)gadStr(g->gHost), sizeof g->saveHost - 1); g->saveHost[sizeof g->saveHost - 1] = '\0'; }
    if (g->gPort) { strncpy(g->savePort, (const char *)gadStr(g->gPort), sizeof g->savePort - 1); g->savePort[sizeof g->savePort - 1] = '\0'; }

    RemoveGList(g->win, &browseGad, 1);
    if (g->glist) {
        RemoveGList(g->win, g->glist, -1);
        FreeGadgets(g->glist);
        g->glist = NULL;
    }
    /* erase old gadget imagery in the interior before re-laying-out */
    SetAPen(g->win->RPort, 0);
    RectFill(g->win->RPort, g->win->BorderLeft, g->win->BorderTop,
             g->win->Width  - g->win->BorderRight  - 1,
             g->win->Height - g->win->BorderBottom - 1);

    if (makeGadgets(g)) {
        AddGList(g->win, g->glist, ~0, -1, NULL);
        RefreshGList(g->glist, g->win, NULL, -1);
        GT_RefreshWindow(g->win, NULL);
        AddGadget(g->win, &browseGad, ~0);
        RefreshGList(&browseGad, g->win, NULL, 1);
    }
    RefreshWindowFrame(g->win);   /* redraw borders/size gadget cleanly */
}

static BOOL buildWindow(struct Gui *g)
{
    struct Screen *sc;
    WORD winw, winh;

    g->scr = LockPubScreen(NULL);
    if (!g->scr) return FALSE;
    g->vi = GetVisualInfo(g->scr, TAG_END);
    if (!g->vi) return FALSE;
    sc = g->scr;
    strcpy(g->status, "Ready");

    winw = 400; if (winw > sc->Width) winw = sc->Width;
    winh = 100; if (winh > sc->Height - sc->BarHeight - 2) winh = sc->Height - sc->BarHeight - 2;

    g->win = OpenWindowTags(NULL,
        WA_Title,     (ULONG)"A314Mount",
        WA_Left,      (sc->Width - winw) / 2, WA_Top, sc->BarHeight + 2,
        WA_Width,     winw, WA_Height, winh,
        WA_MinWidth,  320, WA_MaxWidth, sc->Width,
        WA_MinHeight, winh, WA_MaxHeight, winh,   /* stretch width; height fixed */
        WA_Flags,     WFLG_DRAGBAR | WFLG_DEPTHGADGET | WFLG_CLOSEGADGET |
                      WFLG_SIZEGADGET | WFLG_ACTIVATE,
        WA_IDCMP,     IDCMP_CLOSEWINDOW | IDCMP_REFRESHWINDOW | IDCMP_MENUPICK |
                      IDCMP_NEWSIZE |
                      BUTTONIDCMP | STRINGIDCMP | CYCLEIDCMP | CHECKBOXIDCMP,
        WA_PubScreen, (ULONG)g->scr,
        TAG_END);
    if (!g->win) return FALSE;
    g->prevW = g->win->Width;

    if (makeGadgets(g)) {
        AddGList(g->win, g->glist, ~0, -1, NULL);
        RefreshGList(g->glist, g->win, NULL, -1);
        GT_RefreshWindow(g->win, NULL);
        AddGadget(g->win, &browseGad, ~0);          /* plain image button */
        RefreshGList(&browseGad, g->win, NULL, 1);
    }
    g->menu = CreateMenus(amiNewMenu, TAG_END);
    if (g->menu) {
        if (LayoutMenus(g->menu, g->vi, TAG_END)) SetMenuStrip(g->win, g->menu);
        else { FreeMenus(g->menu); g->menu = NULL; }
    }
    return TRUE;
}

static void closeWin(struct Gui *g)
{
    if (g->win && g->menu) ClearMenuStrip(g->win);
    if (g->menu)  { FreeMenus(g->menu);        g->menu = NULL; }
    if (g->win)   { CloseWindow(g->win);       g->win = NULL; }
    if (g->glist) { FreeGadgets(g->glist);     g->glist = NULL; }
    if (g->vi)    { FreeVisualInfo(g->vi);     g->vi = NULL; }
    if (g->scr)   { UnlockPubScreen(NULL, g->scr); g->scr = NULL; }
}

static void eventLoop(struct Gui *g)
{
    BOOL done = FALSE;
    while (!done) {
        struct IntuiMessage *imsg;
        WaitPort(g->win->UserPort);
        while ((imsg = GT_GetIMsg(g->win->UserPort))) {
            ULONG cls = imsg->Class;
            UWORD code = imsg->Code;
            struct Gadget *gad = (struct Gadget *)imsg->IAddress;
            GT_ReplyIMsg(imsg);

            switch (cls) {
            case IDCMP_CLOSEWINDOW:
                done = TRUE; break;
            case IDCMP_GADGETUP:
                switch (gad->GadgetID) {
                case GAD_DRIVE:  g->drive = code; break;
                case GAD_RW:     g->rw = code ? TRUE : FALSE; break;
                case GAD_INSERT: doOp(g, TRUE);  break;
                case GAD_EJECT:  doOp(g, FALSE); break;
                case GAD_BROWSE: doBrowse(g);    break;
                default: break;
                }
                break;
            case IDCMP_MENUPICK:
                if (code != MENUNULL && g->menu) {
                    struct MenuItem *it = ItemAddress(g->menu, code);
                    if (it && (ULONG)GTMENUITEM_USERDATA(it) == MENU_QUIT) done = TRUE;
                }
                break;
            case IDCMP_NEWSIZE:
                if (g->win->Width != g->prevW) {
                    g->prevW = g->win->Width;
                    rebuildGadgets(g);
                }
                break;
            case IDCMP_REFRESHWINDOW:
                GT_BeginRefresh(g->win); GT_EndRefresh(g->win, TRUE); break;
            default: break;
            }
            if (done) break;
        }
    }
}

int main(void)
{
    struct Gui g;
    int rc = 20;

    memset(&g, 0, sizeof g);
    strcpy(g.saveHost, A314_DEF_HOST);
    strcpy(g.savePort, "23890");
    g.saveAdf[0] = '\0';                 /* empty: pick via the folder browser */

    IntuitionBase = (struct IntuitionBase *)OpenLibrary("intuition.library", 37);
    GfxBase       = (struct GfxBase *)OpenLibrary("graphics.library", 37);
    GadToolsBase  = OpenLibrary("gadtools.library", 37);

    if (IntuitionBase && GfxBase && GadToolsBase && buildWindow(&g)) {
        eventLoop(&g);
        rc = 0;
    }

    closeWin(&g);
    if (GadToolsBase)  CloseLibrary(GadToolsBase);
    if (GfxBase)       CloseLibrary((struct Library *)GfxBase);
    if (IntuitionBase) CloseLibrary((struct Library *)IntuitionBase);
    return rc;
}
